[pytest]
# Run pytest from the finkrit/ directory.
# Prevents crawling into Bazel symlinks and the venv.
testpaths = tests/packages
norecursedirs =
    bazel-bin
    bazel-finkrit
    bazel-out
    bazel-testlogs
    .finkritvenv
    .git
    __pycache__
