# finkritintel/capability/risk.py

from finkritintel.capability.base import Capability
from finkritintel.integration.finkritq import (
    ASSET_BETA_LIVE_BINDING,
    ASSET_CONDITIONAL_VALUE_AT_RISK_LIVE_BINDING,
    ASSET_DOWNSIDE_DEVIATION_LIVE_BINDING,
    ASSET_DRAWDOWN_LIVE_BINDING,
    ASSET_MAXIMUM_DRAWDOWN_LIVE_BINDING,
    ASSET_SEMIVARIANCE_LIVE_BINDING,
    ASSET_VALUE_AT_RISK_LIVE_BINDING,
    ASSET_VARIANCE_LIVE_BINDING,
    ASSET_VOLATILITY_LIVE_BINDING,
    PORTFOLIO_BETA_LIVE_BINDING,
    PORTFOLIO_COMPONENT_CONTRIBUTION_TO_RISK_LIVE_BINDING,
    PORTFOLIO_CONDITIONAL_VALUE_AT_RISK_LIVE_BINDING,
    PORTFOLIO_DOWNSIDE_DEVIATION_LIVE_BINDING,
    PORTFOLIO_DRAWDOWN_LIVE_BINDING,
    PORTFOLIO_MARGINAL_CONTRIBUTION_TO_RISK_LIVE_BINDING,
    PORTFOLIO_MAXIMUM_DRAWDOWN_LIVE_BINDING,
    PORTFOLIO_SEMIVARIANCE_LIVE_BINDING,
    PORTFOLIO_VALUE_AT_RISK_LIVE_BINDING,
    PORTFOLIO_VARIANCE_LIVE_BINDING,
    PORTFOLIO_VOLATILITY_LIVE_BINDING,
)


RISK_CAPABILITY = Capability(
    name="risk_analysis",
    description="Analyze risk for a portfolio or an individual asset.",
    tools=(
        PORTFOLIO_VOLATILITY_LIVE_BINDING,
        PORTFOLIO_VARIANCE_LIVE_BINDING,
        PORTFOLIO_SEMIVARIANCE_LIVE_BINDING,
        PORTFOLIO_DOWNSIDE_DEVIATION_LIVE_BINDING,
        PORTFOLIO_DRAWDOWN_LIVE_BINDING,
        PORTFOLIO_MAXIMUM_DRAWDOWN_LIVE_BINDING,
        PORTFOLIO_VALUE_AT_RISK_LIVE_BINDING,
        PORTFOLIO_CONDITIONAL_VALUE_AT_RISK_LIVE_BINDING,
        PORTFOLIO_BETA_LIVE_BINDING,
        PORTFOLIO_MARGINAL_CONTRIBUTION_TO_RISK_LIVE_BINDING,
        PORTFOLIO_COMPONENT_CONTRIBUTION_TO_RISK_LIVE_BINDING,
        ASSET_VOLATILITY_LIVE_BINDING,
        ASSET_VARIANCE_LIVE_BINDING,
        ASSET_SEMIVARIANCE_LIVE_BINDING,
        ASSET_DOWNSIDE_DEVIATION_LIVE_BINDING,
        ASSET_DRAWDOWN_LIVE_BINDING,
        ASSET_MAXIMUM_DRAWDOWN_LIVE_BINDING,
        ASSET_VALUE_AT_RISK_LIVE_BINDING,
        ASSET_CONDITIONAL_VALUE_AT_RISK_LIVE_BINDING,
        ASSET_BETA_LIVE_BINDING,
    ),
)
